apiVersion: v1
kind: Namespace #kind is the type of Kubernetes resource we want to create. In this case, we want to create a Namespace.
metadata:
  name: roboshop
  labels:
    name: roboshop
    environment: dev
    purpose: poc