apiVersion: v1
kind: Pod
metadata:
  name: lables
  namespace: roboshop
  labels:
    project: roboshop
    component: frontned
    environment: dev
spec:
  containers:
  - name: nginx
    image: nginx