apiVersion: v1
kind: Pod
metadata:
  name: labels
  namespace: roboshop
  labels:
    project: roboshop
    component: frontend
    environment: dev
spec:
  containers:
  - name: nginx
    image: nginx

# Labels are key-value pairs that we can attach to Kubernetes objects, such as pods, services, and deployments.
# They are used to organize and categorize resources in a Kubernetes cluster.
