apiVersion: v1
kind: Pod
metadata:
  name: environment-variables
  namespace: roboshop
spec:
  containers:
  - name: nginx
    image: nginx
  env:
  - name: ENV
    value: DEV

# env is used to set environment variables in the container, it is key-value pair.
# similar like settings to the container. Before the container start set the env inside it.

