apiVersion: v1
kind: Pod
metadata:
  name: pod-secret-demo
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
    envFrom:
      - secretRef:
          name: nginx-secret # References the name of your Secret (from 10-secrets.yaml)

# pod-secret-demo is a pod that demonstrates how to use a Secret to set environment variables for a container.
# The container is having  resource requests and limits defined for memory and CPU. 
# The envFrom field is used to specify that environment variables should be sourced from a Secret named nginx-secret.
