apiVersion: v1
kind: Pod
metadata:
  name: pod-secret-demo
spec:
  containers:
    - name: nginx
      image: nginx
      envFrom:
        - secretRef:
            name: nginx-secret # References the name of your Secret here 10-secrets.yaml
